### ISSUE TITLE
I tried to install but error arise node init-db.js. Says it sqlite drive maybe isn't installed

### ISSUE THREAD

**Issue by jechaviz** [dashersw/cote-workshop#12]
Thank you so much..

Error ORMError: Connection protocol not supported - have you installed the database driver for sqlite?       
    at Object.exports.connect (C:\Users\L\Downloads\code\js\cote-workshop\node_modules\orm\lib\ORM.js:131:24)
    at Object.<anonymous> (C:\Users\L\Downloads\code\js\cote-workshop\models.js:10:14)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at Object.<anonymous> (C:\Users\L\Downloads\code\js\cote-workshop\init-db.js:1:14)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:72:12)
    at node:internal/main/run_main_module:17:47 {
  code: 4,
  literalCode: 'NO_SUPPORT'
}

**Comment by nyeroglu** [comment]
**Because of [ABI](https://stackoverflow.com/a/3784697) differences, Sqlite3 must be built in a custom to used with node-webkit(nw).**
If you have nw-gyp installed, npm update may solves the problem, it will recompile depends on your arch.
https://www.npmjs.com/package/sqlite3#building-for-node-webkit
