### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by GHNewbiee** [dashersw/cote-workshop#8]
Plenty errors!

```
npm WARN deprecated letsencrypt@2.1.9: letsencrypt has been renamed to greenlock. Please find it at npm greenlock
npm WARN deprecated safetimeout@0.1.2: Please use the 'safe-timers' module instead
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated localhost.daplie.com-certificates@1.2.5: this package has been deprecated
npm WARN deprecated uws@9.14.0: stop using this version

../src/ursaNative.cc:389:13: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
...
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.15.0-23-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pavlos/SharedFolder/Frameworks/cote/cote-workshop-0.13.2/node_modules/ursa
gyp ERR! node -v v10.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.5.0 (node-v64 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.5.0 (node-v64 ABI) (falling back to source compile with node-gyp) 

../node_modules/nan/nan_maybe_43_inl.h:112:15: error: ‘class v8::Object’ has no member named ‘ForceSet’

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
I use node 10.5.0

Tia

**Comment by dashersw** [comment]
Hello! I updated the dependencies and re-installed. Can you check it again?

**Comment by GHNewbiee** [comment]
Hi,

There is still problem with `node-gyp rebuild`, but it does work!

Thanks.
